const ADD_TRANS = 'ADD_TRANS';
const REMOVE_TRANS = 'REMOVE_TRANS';
const GET_PLN_VALUE = 'GET_PLN_VALUE';
const ADD_ID = 'ADD_ID';

export default {
  ADD_TRANS,
  REMOVE_TRANS,
  GET_PLN_VALUE,
  ADD_ID,
};
