const ADD_TRANS = 'ADD_TRANS';
const REMOVE_TRANS = 'REMOVE_TRANS';
const GET_PLN_VALUE = 'GET_PLN_VALUE';
const ADD_ID = 'ADD_ID';
const UPDATE_TRANS = 'UPDATE_TRANS';
const ERROR = 'ERROR';
const REMOVE_ERROR = 'REMOVE ERROR';
const UPDATE_EURO = 'UPDATE_EURO';
const UPDATE_PLN = 'UPDATE_PLN';
const UPDATE_TRANS_NAME = 'UPDATE_TRANS_NAME';

export default {
  ADD_TRANS,
  REMOVE_TRANS,
  GET_PLN_VALUE,
  ADD_ID,
  UPDATE_TRANS,
  ERROR,
  REMOVE_ERROR,
  UPDATE_TRANS_NAME,
  UPDATE_PLN,
  UPDATE_EURO,
};
