const ADD_TRANS = 'ADD_TRANS';
const REMOVE_TRANS = 'REMOVE_TRANS';
const GET_PLN_VALUE = 'GET_PLN_VALUE';
const ADD_ID = 'ADD_ID';
const UPDATE_TRANS = 'UPDATE_TRANS';
const ERROR = 'ERROR';
const REMOVE_ERROR = 'REMOVE ERROR';

export default {
  ADD_TRANS,
  REMOVE_TRANS,
  GET_PLN_VALUE,
  ADD_ID,
  UPDATE_TRANS,
  ERROR,
  REMOVE_ERROR,
};
